### ISSUE TITLE
Exception in parallel execution

### ISSUE THREAD

**Issue by XDsubhash** [red-hat-storage/cephci#102]
```
2020-04-22 09:46:45,669 - mita.openstack - INFO -  ... available
2020-04-22 09:46:45,670 - mita.openstack - INFO - Attaching volume ceph-rhceph-jslave1-1587562779221-node12-osd2...
2020-04-22 09:46:47,023 - mita.openstack - INFO - Successfully attached volume ceph-rhceph-jslave1-1587562779221-node12-osd2
2020-04-22 09:46:47,023 - mita.openstack - INFO - Creating 15gb of storage for: ceph-rhceph-jslave1-1587562779221-node12-osd3
2020-04-22 09:46:47,628 - mita.openstack - INFO - Waiting for volume ceph-rhceph-jslave1-1587562779221-node12-osd3 to become available
2020-04-22 09:46:47,628 - mita.openstack - INFO - Volume: ceph-rhceph-jslave1-1587562779221-node12-osd3 is in state: creating
2020-04-22 09:47:02,314 - mita.openstack - INFO - Waiting for node ceph-rhceph-jslave1-1587562779221-node10-pool to become available
2020-04-22 09:47:05,614 - mita.openstack - INFO - Failed to bring the node in running state in 0:04:00s
2020-04-22 09:47:06,571 - mita.openstack - INFO -  ... available
2020-04-22 09:47:06,571 - mita.openstack - INFO - Attaching volume ceph-rhceph-jslave1-1587562779221-node12-osd3...
2020-04-22 09:47:07,348 - mita.openstack - INFO - Successfully attached volume ceph-rhceph-jslave1-1587562779221-node12-osd3
2020-04-22 09:47:17,354 - ceph.parallel - ERROR - Exception in parallel execution
Traceback (most recent call last):
  File "/home/rhceph-jslave1/workspace/rhceph-ansible-sanity-4.1-rhel7.8/ceph/parallel.py", line 87, in __exit__
    for result in self:
  File "/home/rhceph-jslave1/workspace/rhceph-ansible-sanity-4.1-rhel7.8/ceph/parallel.py", line 105, in __next__
    resurrect_traceback(result)
  File "/home/rhceph-jslave1/workspace/rhceph-ansible-sanity-4.1-rhel7.8/ceph/parallel.py", line 34, in resurrect_traceback
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "/home/rhceph-jslave1/workspace/rhceph-ansible-sanity-4.1-rhel7.8/ceph/parallel.py", line 21, in capture_traceback
    return func(*args, **kwargs)
  File "/home/rhceph-jslave1/workspace/rhceph-ansible-sanity-4.1-rhel7.8/ceph/utils.py", line 81, in setup_vm_node
    ceph_nodes[node] = CephVMNode(**params)
  File "/home/rhceph-jslave1/workspace/rhceph-ansible-sanity-4.1-rhel7.8/mita/openstack.py", line 70, in __init__
    self.create_node()
  File "/home/rhceph-jslave1/workspace/rhceph-ansible-sanity-4.1-rhel7.8/mita/openstack.py", line 170, in create_node
    raise NodeErrorState("Failed to bring up the node in Running state " + self.name)
AttributeError: 'CephVMNode' object has no attribute 'name'
/home/rhceph-jslave1/workspace/rhceph-ansible-sanity-4.1-rhel7.8/utility/utils.py:612: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = yaml.load(yml)
Traceback (most recent call last):
  File "run.py", line 611, in <module>
    rc = run(args)
  File "run.py", line 413, in run
    ceph_cluster_dict, clients = create_nodes(conf, inventory, osp_cred, run_id, service, instances_name)
  File "/home/rhceph-jslave1/workspace/rhceph-ansible-sanity-4.1-rhel7.8/utility/retry.py", line 25, in f_retry
    return f(*args, **kwargs)
  File "run.py", line 137, in create_nodes
    ceph_vmnodes = create_ceph_nodes(cluster, inventory, osp_cred, run_id, instances_name)
  File "/home/rhceph-jslave1/workspace/rhceph-ansible-sanity-4.1-rhel7.8/ceph/utils.py", line 75, in create_ceph_nodes
    p.spawn(setup_vm_node, node, ceph_nodes, **node_params)
  File "/home/rhceph-jslave1/workspace/rhceph-ansible-sanity-4.1-rhel7.8/ceph/parallel.py", line 87, in __exit__
    for result in self:
  File "/home/rhceph-jslave1/workspace/rhceph-ansible-sanity-4.1-rhel7.8/ceph/parallel.py", line 105, in __next__
    resurrect_traceback(result)
  File "/home/rhceph-jslave1/workspace/rhceph-ansible-sanity-4.1-rhel7.8/ceph/parallel.py", line 34, in resurrect_traceback
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "/home/rhceph-jslave1/workspace/rhceph-ansible-sanity-4.1-rhel7.8/ceph/parallel.py", line 21, in capture_traceback
    return func(*args, **kwargs)
  File "/home/rhceph-jslave1/workspace/rhceph-ansible-sanity-4.1-rhel7.8/ceph/utils.py", line 81, in setup_vm_node
    ceph_nodes[node] = CephVMNode(**params)
  File "/home/rhceph-jslave1/workspace/rhceph-ansible-sanity-4.1-rhel7.8/mita/openstack.py", line 70, in __init__
    self.create_node()
  File "/home/rhceph-jslave1/workspace/rhceph-ansible-sanity-4.1-rhel7.8/mita/openstack.py", line 170, in create_node
    raise NodeErrorState("Failed to bring up the node in Running state " + self.name)
AttributeError: 'CephVMNode' object has no attribute 'name'
```
https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhceph-ansible-sanity-4.1-rhel7.8/36/console

**Comment by XDsubhash** [comment]
Failed to bring the node in running state in 0:04:00s--> add ip/node name to log msg and increase timeout to 5_6 mins(in osp UI they are up)

**Comment by psathyan** [comment]
@veera-raghava-reddy I believe we can close this issue. The latest code handles this case.
