### ISSUE TITLE
run.py fails to find RPM compose source with `--rhbuild 5.1-rhel-8`

### ISSUE THREAD

**Issue by andrewschoen** [red-hat-storage/cephci#1096]
When using `--rhbuild 5.1-rhel-8` run.py fails with the following:

```
run.py --rhbuild 5.1-rhel-8 --global-conf conf/pacific/cephadm/sanity-cephadm.yaml --osp-cred /home/jenkins-build/workspace/ceph-test-cephci/.osp-cred.yaml --inventory conf/inventory/rhel-8.2-server-x86_64.yaml --suite suites/pacific/cephadm/tier_0_cephadm.yaml --ignore-latest-container --log-level info --insecure-registry --hotfix-repo http://brew-task-repos.usersys.redhat.com/repos/scratch/ceph-build/ceph/16.2.7/27.0.TEST.rhbz_2041660_5.1.el8cp/ceph-16.2.7-27.0.TEST.rhbz_2041660_5.1.el8cp-scratch.repo --docker-registry registry-proxy.engineering.redhat.com --docker-image rh-osbs/rhceph --docker-tag ceph-5.1-rhel-8-containers-candidate-84768-20220118052720

2022-01-18 05:57:05,331 - __main__ - INFO - RPM Compose source - None
2022-01-18 05:57:05,331 - __main__ - INFO - Red Hat Ceph Image used - registry-proxy.engineering.redhat.com/rh-osbs/rhceph:ceph-5.1-rhel-8-containers-candidate-84768-20220118052720
Traceback (most recent call last):
  File "run.py", line 1114, in <module>
    rc = run(args)
  File "run.py", line 626, in run
    resp = requests.get(base_url + "/COMPOSE_ID", verify=False)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

When I rerun with the same container and `--rhbuild 5.0-rhel-8` the command succeeds:

```
run.py --rhbuild 5.0-rhel-8 --global-conf conf/pacific/cephadm/sanity-cephadm.yaml --osp-cred /home/jenkins-build/workspace/ceph-test-cephci/.osp-cred.yaml --inventory conf/inventory/rhel-8.2-server-x86_64.yaml --suite suites/pacific/cephadm/tier_0_cephadm.yaml --ignore-latest-container --log-level info --insecure-registry --hotfix-repo http://brew-task-repos.usersys.redhat.com/repos/scratch/ceph-build/ceph/16.2.7/27.0.TEST.rhbz_2041660_5.1.el8cp/ceph-16.2.7-27.0.TEST.rhbz_2041660_5.1.el8cp-scratch.repo --docker-registry registry-proxy.engineering.redhat.com --docker-image rh-osbs/rhceph --docker-tag ceph-5.1-rhel-8-containers-candidate-84768-20220118052720

2022-01-18 16:10:43,056 - __main__ - INFO - RPM Compose source - http://download.eng.bos.redhat.com/rhel-8/composes/auto/ceph-5.0-rhel-8/latest-RHCEPH-5-RHEL-8/
2022-01-18 16:10:43,057 - __main__ - INFO - Red Hat Ceph Image used - registry-proxy.engineering.redhat.com/rh-osbs/rhceph:ceph-5.1-rhel-8-containers-candidate-84768-20220118052720
2022-01-18 16:10:43,184 - __main__ - INFO - Compose id is: RHCEPH-5.0-RHEL-8-20220107.ci.1
2022-01-18 16:10:43,184 - __main__ - INFO - Testing Ceph Version: 16.2.0-150.el8cp
2022-01-18 16:10:43,184 - __main__ - INFO - Testing Ceph Ansible Version: 6.0.20.2-1.el8cp.noarch
...
```

**Comment by psathyan** [comment]
Unofficially, we have started to depreciate the usage of `rhbuild.yaml` as the source of build artifacts within the framework. Due to this practice, we have not updated `5.1-rhel-8` details in this file. This is the reason why one would observe the error `TypeError: unsupported operand` when using `--rhbuild 5.1-rhel-8`.

Presently, we recommend using `--v2` argument along with `--rhbuild <major>.<minor> --platform rhel-8`. These arguments allows us to pick the location of build artifacts based on the value provided with `--build <latest|tier-0|tier-1|released>`

```
latest -> read the latest development build
tier-0 -> latest stable build that has passed tier-0 test stage
tier-1 -> latest build that has passed tier-1 test stage
released -> CDN
```

For example, to run the a test using the latest RHCS 5.1 build
```
python run.py --v2 \
  --rhbuild 5.1\
  --platform rhel-8 \
  --build latest \
  --global-conf conf/pacific/rbd/tier-0_rbd.yaml \
  --inventory conf/inventory/rhel-8.5-server-x86_64.yaml \
  --suite suites/pacific/rbd/tier-2_rbd_regression.yaml \
  --osp-cred osp-cred-ci-2.yaml
```

In the above example, the framework would picks the build artifact information from the `latest` section found in http://magna002.ceph.redhat.com/cephci-jenkins/latest-rhceph-container-info/RHCEPH-5.1.yaml

In this file, we maintain the latest compose and image details hence reducing the number of parameters required to be passed.

With this approach, we have the ability to execute tests outside of Red Hat network by using `build-url` config in `cephci.yaml` to provide the location to read build artifacts.

With that being said, would it be possible to modify the CLI arguments at your end? For example

```
python run.py \
    --v2 \
    --rhbuild 5.1 \
    --platform rhel-8 \
    --build latest \
    --global-conf conf/pacific/cephadm/sanity-cephadm.yaml \
    --osp-cred .osp-cred.yaml \
    --inventory conf/inventory/rhel-8-latest.yaml \
    --suite suites/pacific/cephadm/tier_0_cephadm.yaml \
    --log-level info \
    --add-repo http://brew-task-repos.usersys.redhat.com/repos/scratch/ceph build/ceph/16.2.7/27.0.TEST.rhbz_2041660_5.1.el8cp/ceph-16.2.7-27.0.TEST.rhbz_2041660_5.1.el8cp-scratch.repo
```

**Comment by psathyan** [comment]
@andrewschoen Please feel free to reopen the issue if the query is not addressed.

**Comment by andrewschoen** [comment]
@psathyan I added those additional flags and the command got further. We use ``--hotfix-repo`` and the ``--docker-*`` flags though so I think most of them are noop though.

The next issue I hit was related to emailing test results. We had removed the `email` setting from cephci.yaml to avoid sending emails entirely, I still saw this failure though.

```
Traceback (most recent call last):
  File "run.py", line 1117, in <module>
    rc = run(args)
  File "run.py", line 1057, in run
    email_results(test_result=test_res)
  File "/home/jenkins-build/workspace/ceph-test-cephci/utility/utils.py", line 723, in email_results
    suite=results_list[0]["suite-name"],
IndexError: list index out of range
```

Is there still a way to disable emailing of the results or a way to avoid this?

**Comment by psathyan** [comment]
The error `IndexError` would occur when the provided test suite is invalid or contains no `tests` section. I believe the name of the suite file is `suites/pacific/cephadm/tier-0_cephadm.yaml`

**Comment by andrewschoen** [comment]
Thanks, that fixed it. I've opened https://github.com/red-hat-storage/cephci/issues/1112 as a suggestion to make debugging similar situations easier.
