### ISSUE TITLE
cvp suite failing with multiple errors

### ISSUE THREAD

**Issue by subhashp7i** [red-hat-storage/cephci#152]
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1593660428018/containerized_ceph_ansible_0.log

**Comment by XDsubhash** [comment]
another image pulling failure : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1593664250332/containerized_ceph_ansible_0.log

**Comment by XDsubhash** [comment]
failed few times with this error: https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhceph-cvp-external-gating-test/26/console

```2020-07-02 08:21:21,934 - ceph.ceph - INFO - Running command sudo ceph -s -f json on 10.0.103.132
2020-07-02 08:21:22,407 - ceph.ceph - INFO - Command completed successfully
2020-07-02 08:21:22,410 - ceph.ceph - INFO - All osds are up and in
2020-07-02 08:21:22,410 - ceph.ceph - INFO - 4
2020-07-02 08:21:22,411 - ceph.ceph - INFO - 4
2020-07-02 08:21:22,411 - __main__ - INFO - Test <module 'test_ansible_roll_over' from '/home/rhceph-jslave1/workspace/rhceph-cvp-external-gating-test/tests/test_ansible_roll_over.py'> passed
Test <module 'test_ansible_roll_over' from '/home/rhceph-jslave1/workspace/rhceph-cvp-external-gating-test/tests/test_ansible_roll_over.py'> passed
2020-07-02 08:21:22,415 - utility.polarion - INFO - Updating test run: 14_2_4-125_el8cp_sanity_rhceph_base_container_rhel-8_2_0-x86_64-released_Automated_Smoke_Runs 
2020-07-02 08:21:22,421 - utility.polarion - INFO - updating results for CEPH-9582 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1009  100    80  100   929    324   3771 --:--:-- --:--:-- --:--:--  3776
{
  "files" : {
    "tmpf57gx5en" : {
      "job-ids" : [ 1114731 ]
    }
  }
}
/home/rhceph-jslave1/workspace/rhceph-cvp-external-gating-test/utility/utils.py:612: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = yaml.load(yml)
/home/rhceph-jslave1/workspace/rhceph-cvp-external-gating-test/lib64/python3.6/site-packages/paramiko/kex_ecdh_nist.py:39: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  m.add_string(self.Q_C.public_numbers().encode_point())
/home/rhceph-jslave1/workspace/rhceph-cvp-external-gating-test/lib64/python3.6/site-packages/paramiko/kex_ecdh_nist.py:96: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  self.curve, Q_S_bytes
/home/rhceph-jslave1/workspace/rhceph-cvp-external-gating-test/lib64/python3.6/site-packages/paramiko/kex_ecdh_nist.py:111: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  hm.add_string(self.Q_C.public_numbers().encode_point())
Traceback (most recent call last):
  File "run.py", line 604, in <module>
    rc = run(args)
  File "run.py", line 443, in run
    tc['name'] = test.get('name')
AttributeError: 'NoneType' object has no attribute 'get'
Build step 'Execute shell' marked build as failure```

**Comment by tintumathew10** [comment]
Closing this issue as new CVP job is in place.
