### ISSUE TITLE
upgrade from 4x to 5x multisite fails with  KeyError: 'ceph-rgw1' 

### ISSUE THREAD

**Issue by Ameenasuhani** [red-hat-storage/cephci#1522]
**Describe the bug**
Upgrade from 4x to 5x multisite fails to collect recipe file 

**To Reproduce**
#python run.py --osp-cred osp/osp-cred-ci-2.yaml --global-conf conf/pacific/upgrades/tier-1_upgrade_cephadm.yaml --suite suites/pacific/upgrades/tier-1_upgrade_4x-to-5x-multisite.yaml --inventory conf/inventory/rhel-8.5-server-x86_64.yaml --log-level debug --platform rhel-8 --build latest --rhbuild 5.2 --store --skip-sos-report --report-portal

**Expected behavior**
the suite should run successfully and multi site should be upgraded

**Logs**
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-K30ZKM/ceph-ansible_deployment_0.log
**Environment**
A concise description of your environment: RHEL version,
python version, operating system, command used etc.

**Additional context**
Traceback (most recent call last):
  File "/home/amsyedha/bz2092905/cephci/lib64/python3.6/site-packages/reportportal_client/service.py", line 564, in _log_batch
    timeout=self.http_timeout)
  File "/home/amsyedha/bz2092905/cephci/lib64/python3.6/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/amsyedha/bz2092905/cephci/lib64/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/amsyedha/bz2092905/cephci/lib64/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/amsyedha/bz2092905/cephci/lib64/python3.6/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='cistatus.ceph.redhat.com', port=80): Max retries exceeded with url: /api/v2/cephci/log (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8656446b10>, 'Connection to cistatus.ceph.redhat.com timed out. (connect timeout=10)'))
2022-06-07 01:44:59,047 - ERROR - cephci.test_ansible:110 - 'ceph-rgw1'
Traceback (most recent call last):
  File "run.py", line 834, in run
    ceph_cluster_dict[cluster_name].rhcs_version = _rhcs_version
KeyError: 'ceph-rgw1'
Traceback (most recent call last):
  File "run.py", line 1026, in <module>
    rc = run(args)
  File "run.py", line 849, in run
    collect_recipe(ceph_cluster_dict[cluster_name])
KeyError: 'ceph-rgw1'

**Comment by psathyan** [comment]
@mkasturi18 would you be able to help here?

**Comment by mkasturi18** [comment]
@Ameenasuhani , The KeyError seen is due to the conf file used. For multisite deployment the conf file is https://github.com/red-hat-storage/cephci/blob/master/conf/pacific/rgw/rgw_multisite.yaml

**Comment by mkasturi18** [comment]
The conf file conf/pacific/upgrades/tier-1_upgrade_cephadm.yaml did not have multisite deployment included. Hence the failure. Closing this ticket
