### ISSUE TITLE
Intermittent OrchApplyServiceFailure issue is observed in RADOS suites

### ISSUE THREAD

**Issue by tintumathew10** [red-hat-storage/cephci#1523]
**Describe the bug**
Observing intermittent failure in rados test suite execution while cluster deployment is in progress.

2022-06-08 03:58:12,078 - ERROR - cephci.test_cephadm:110 - mgr failed with 
['2022-06-08T03:28:03.988804Z service:mgr [INFO] "service was created"']
2022-06-08 03:58:12,078 - ERROR - cephci.test_cephadm:110 - mgr
Traceback (most recent call last):
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline/tests/ceph_installer/test_cephadm.py", line 130, in run
    func(cfg)
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline/ceph/ceph_admin/mgr.py", line 41, in apply
    super().apply(config=config)
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline/ceph/ceph_admin/apply.py", line 128, in apply
    raise OrchApplyServiceFailure(self.SERVICE_NAME)
ceph.ceph_admin.apply.OrchApplyServiceFailure: mgr

some of the tests are failing for mon also

2022-06-03 20:01:00,870 - ERROR - cephci.test_cephadm:110 - mon failed with 
['2022-06-03T19:30:46.056475Z service:mon [INFO] "service was created"']
2022-06-03 20:01:00,872 - ERROR - cephci.test_cephadm:110 - mon
Traceback (most recent call last):
  File "/home/jenkins-build/workspace/rhceph-cron-pipeline-test-executor/tests/ceph_installer/test_cephadm.py", line 130, in run
    func(cfg)
  File "/home/jenkins-build/workspace/rhceph-cron-pipeline-test-executor/ceph/ceph_admin/mon.py", line 39, in apply
    super().apply(config=config)
  File "/home/jenkins-build/workspace/rhceph-cron-pipeline-test-executor/ceph/ceph_admin/apply.py", line 128, in apply
    raise OrchApplyServiceFailure(self.SERVICE_NAME)
ceph.ceph_admin.apply.OrchApplyServiceFailure: mon

logs:
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-G62CV2/
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-M4Q35Y/
https://159.23.92.24/blue/rest/organizations/jenkins/pipelines/rhceph-test-execution-pipeline/runs/65/nodes/62/steps/87/log/?start=0

**Comment by pdhiran** [comment]
https://159.23.92.24/blue/rest/organizations/jenkins/pipelines/rhceph-test-execution-pipeline/runs/50/nodes/62/steps/87/log/?start=0

``` 
2022-06-03 12:13:01,839 - INFO - cephci.test_cephadm:110 - 3/3 mgr up... retrying
2022-06-03 12:13:21,840 - INFO - cephci.test_cephadm:110 - Running command cephadm -v shell -- ceph orch  --format json ls  --refresh --service_name mgr on 10.245.7.204 timeout 600
2022-06-03 12:13:23,844 - INFO - cephci.test_cephadm:110 - Command completed successfully
2022-06-03 12:13:23,844 - DEBUG - cephci.test_cephadm:110 - 
[{"events": ["2022-06-03T11:43:40.768511Z service:mgr [INFO] \"service was created\""], "placement": {"label": "mgr"}, "service_name": "mgr", "service_type": "mgr", "status": {"created": "2022-06-03T11:43:40.698608Z", "last_refresh": "2022-06-03T12:13:03.523242Z", "running": 3, "size": 3}}]

2022-06-03 12:13:23,845 - INFO - cephci.test_cephadm:110 - 3/3 mgr up... retrying
2022-06-03 12:13:43,845 - INFO - cephci.test_cephadm:110 - Running command cephadm -v shell -- ceph orch  --format json ls  --refresh --service_name mgr on 10.245.7.204 timeout 600
2022-06-03 12:13:45,837 - INFO - cephci.test_cephadm:110 - Command completed successfully
2022-06-03 12:13:45,838 - DEBUG - cephci.test_cephadm:110 - 
[{"events": ["2022-06-03T11:43:40.768511Z service:mgr [INFO] \"service was created\""], "placement": {"label": "mgr"}, "service_name": "mgr", "service_type": "mgr", "status": {"created": "2022-06-03T11:43:40.698608Z", "last_refresh": "2022-06-03T12:13:25.537733Z", "running": 3, "size": 3}}]

2022-06-03 12:13:45,838 - INFO - cephci.test_cephadm:110 - 3/3 mgr up... retrying
2022-06-03 12:13:45,838 - INFO - cephci.test_cephadm:110 - Running command cephadm -v shell -- ceph orch  --format json ls  --refresh --service_name mgr on 10.245.7.204 timeout 600
2022-06-03 12:13:48,302 - INFO - cephci.test_cephadm:110 - Command completed successfully
2022-06-03 12:13:48,302 - DEBUG - cephci.test_cephadm:110 - 
[{"events": ["2022-06-03T11:43:40.768511Z service:mgr [INFO] \"service was created\""], "placement": {"label": "mgr"}, "service_name": "mgr", "service_type": "mgr", "status": {"created": "2022-06-03T11:43:40.698608Z", "last_refresh": "2022-06-03T12:13:27.394794Z", "running": 3, "size": 3}}]

2022-06-03 12:13:48,302 - ERROR - cephci.test_cephadm:110 - mgr failed with 
['2022-06-03T11:43:40.768511Z service:mgr [INFO] "service was created"']
2022-06-03 12:13:48,303 - ERROR - cephci.test_cephadm:110 - mgr
Traceback (most recent call last):
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline/tests/ceph_installer/test_cephadm.py", line 130, in run
    func(cfg)
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline/ceph/ceph_admin/mgr.py", line 41, in apply
    super().apply(config=config)
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline/ceph/ceph_admin/apply.py", line 128, in apply
    raise OrchApplyServiceFailure(self.SERVICE_NAME)
ceph.ceph_admin.apply.OrchApplyServiceFailure: mgr 
```

**Comment by psathyan** [comment]
Thanks for raising this issue. We believe that the failure is caused by VMs having IP addresses from different subnet. The concerning part is that we are seeing the issue with IBM-C environment. Here there exists only one subnet.

This brings up the question is it a framework issue.

**Comment by pdhiran** [comment]
Facing the issue more often now : http://magna002.ceph.redhat.com/ceph-qe-logs/pawan/cephci-run-EPKXM7/

**Comment by tintumathew10** [comment]
same issue observed in 15/06/2020 regression run.- https://159.23.92.24/blue/rest/organizations/jenkins/pipelines/rhceph-test-execution-pipeline/runs/108/nodes/68/steps/93/log/?start=0

**Comment by tintumathew10** [comment]
tier-2-stage-4 | 4. Stretch mode regression
tier-2-stage-2 | 3. Ec pool osd rebalance

deployment failed with ceph.ceph_admin.apply.OrchApplyServiceFailure: mgr

**Comment by tintumathew10** [comment]
tier-2-stage-4 | 4. Stretch mode regression - failing even after this PR is merged.
https://github.com/red-hat-storage/cephci/pull/1553

https://159.23.92.24/blue/rest/organizations/jenkins/pipelines/rhceph-test-execution-pipeline/runs/227/nodes/59/steps/84/log/?start=0
