### ISSUE TITLE
RHCEPH 4.3 cluster deployment failed on baremetal.

### ISSUE THREAD

**Issue by tintumathew10** [red-hat-storage/cephci#1536]
Trying to deploy RHCEPH 4.3 cluster using cephci failed with error "Devices have inconsistent logical block sizes (512 and 4096)"

2022-06-13 09:36:47,645 - ERROR - cephci.test_ansible:110 - Error 5 during cmd, timeout 600
2022-06-13 09:36:47,645 - ERROR - cephci.test_ansible:110 - sudo vgcreate vg1 /dev/sdb /dev/sdc /dev/sdd /dev/sde /dev/sdf /dev/nvme0n1 Error:    Devices have inconsistent logical block sizes (512 and 4096).
 10.8.129.208
Traceback (most recent call last):
  File "run.py", line 843, in run
    clients=clients,
  File "/home/tmathew/ceph/cephci/tests/ceph_installer/test_ansible.py", line 106, in run
    device_to_add, mixed_lvm_configs, filestore
  File "/home/tmathew/ceph/cephci/ceph/ceph.py", line 309, in generate_ansible_inventory
    devices, lvm_utils.osd_scenario_list[osd_scenario]
  File "/home/tmathew/ceph/cephci/ceph/ceph.py", line 2006, in multiple_lvm_scenarios
    generated_sce_dict = scenario(self, devices_dict)
  File "/home/tmathew/ceph/cephci/utility/lvm_utils.py", line 36, in osd_scenario1
    osd, osd.LvmConfig.vg_name % "1", devices_dict.get("devices")
  File "/home/tmathew/ceph/cephci/utility/lvm_utils.py", line 6, in vgcreate
    osd.exec_command(cmd="sudo vgcreate %s %s" % (vg_name, devices))
  File "/home/tmathew/ceph/cephci/ceph/ceph.py", line 1550, in exec_command
    f"{kw['cmd']} Error:  {str(stderr)} {str(self.ip_address)}"
ceph.ceph.CommandFailed: sudo vgcreate vg1 /dev/sdb /dev/sdc /dev/sdd /dev/sde /dev/sdf /dev/nvme0n1 Error:    Devices have inconsistent logical block sizes (512 and 4096).
 10.8.129.208

logs:
http://magna002.ceph.redhat.com/ceph-qe-logs/tmathew/cephci-run-PM33ZE/

**Comment by tintumathew10** [comment]
https://access.redhat.com/solutions/5822381
To use two different block sizes in same VG, enable allow_mixed_block_sizes in lvm.conf file.

[root@bruuni004 lvm]# cat lvm.conf | grep allow_mixed_block_sizes
	# Configuration option devices/allow_mixed_block_sizes.
	allow_mixed_block_sizes = 0
[root@bruuni004 lvm]# lsblk
NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda       8:0    0 447.1G  0 disk 
└─sda1    8:1    0 447.1G  0 part /
sdb       8:16   0 894.3G  0 disk 
sdc       8:32   0 894.3G  0 disk 
sdd       8:48   0 894.3G  0 disk 
sde       8:64   0   1.8T  0 disk 
sdf       8:80   0   1.8T  0 disk 
nvme0n1 259:0    0   1.5T  0 disk 
[root@bruuni004 lvm]#
