### ISSUE TITLE
OCI runtime error is observed in rados cron pipeline execution

### ISSUE THREAD

**Issue by tintumathew10** [red-hat-storage/cephci#1539]
This error is observed one time in the rados cron pipeline execution.

Error:Error: OCI runtime error: runc: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: Unit libpod-06408c7e42ff4b01a71c0e7ccb0a386335823886846d92b219b8ccca24e2b981.scope not found.
 10.0.210.25
Traceback (most recent call last):
  File "/home/jenkins-build/workspace/rhceph-cron-pipeline-test-executor/tests/ceph_installer/test_cephadm.py", line 130, in run
    func(cfg)
  File "/home/jenkins-build/workspace/rhceph-cron-pipeline-test-executor/ceph/ceph_admin/host.py", line 168, in add_hosts
    self.add(cfg)
  File "/home/jenkins-build/workspace/rhceph-cron-pipeline-test-executor/ceph/ceph_admin/host.py", line 108, in add
    self.shell(args=cmd)
  File "/home/jenkins-build/workspace/rhceph-cron-pipeline-test-executor/ceph/ceph_admin/shell.py", line 53, in shell
    long_running=long_running,
  File "/home/jenkins-build/workspace/rhceph-cron-pipeline-test-executor/ceph/ceph.py", line 2053, in exec_command
    return self.node.exec_command(cmd=cmd, **kw)
  File "/home/jenkins-build/workspace/rhceph-cron-pipeline-test-executor/ceph/ceph.py", line 1550, in exec_command
    f"{kw['cmd']} Error:  {str(stderr)} {str(self.ip_address)}"
ceph.ceph.CommandFailed: cephadm -v shell -- ceph orch host add ceph-ci-m87uw-gp2ptj-node3 10.0.211.202 node-exporter osd crash Error:  --------------------------------------------------------------------------------: runc: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: Unit libpod-06408c7e42ff4b01a71c0e7ccb0a386335823886846d92b219b8ccca24e2b981.scope not found.
 10.0.210.25
Traceback (most recent call last):
  File "/home/jenkins-build/workspace/rhceph-cron-pipeline-test-executor/tests/ceph_installer/test_cephadm.py", line 130, in run
    func(cfg)
  File "/home/jenkins-build/workspace/rhceph-cron-pipeline-test-executor/ceph/ceph_admin/host.py", line 168, in add_hosts
    self.add(cfg)
  File "/home/jenkins-build/workspace/rhceph-cron-pipeline-test-executor/ceph/ceph_admin/host.py", line 108, in add
    self.shell(args=cmd)
  File "/home/jenkins-build/workspace/rhceph-cron-pipeline-test-executor/ceph/ceph_admin/shell.py", line 53, in shell
    long_running=long_running,
  File "/home/jenkins-build/workspace/rhceph-cron-pipeline-test-executor/ceph/ceph.py", line 2053, in exec_command
    return self.node.exec_command(cmd=cmd, **kw)
  File "/home/jenkins-build/workspace/rhceph-cron-pipeline-test-executor/ceph/ceph.py", line 1550, in exec_command
    f"{kw['cmd']} Error:  {str(stderr)} {str(self.ip_address)}"
ceph.ceph.CommandFailed: cephadm -v shell -- ceph orch host add ceph-ci-m87uw-gp2ptj-node3 10.0.211.202 node-exporter osd crash Error:  --------------------------------------------------------------------------------

logs:

http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-GP2PTJ/cluster_deployment_0.log

**Comment by psathyan** [comment]
How reproducible is this issue?

**Comment by tintumathew10** [comment]
Pipeline changes are introduced and this is no more a n issue.
