### ISSUE TITLE
Multipath upgrade fails while upgrading from 3.3 to 4.2

### ISSUE THREAD

**Issue by manasagowri** [red-hat-storage/cephci#1592]
Upgrading from RHCS 3.3 to 4.2 failed with the following error.

2022-07-01 19:48:08,889 - INFO - cephci.test_upgrade:110 - Starting Ceph cluster upgrade
2022-07-01 19:48:08,889 - INFO - cephci.test_upgrade:110 - Upgrading Ceph cluster from version 3.3 to version 4.2
2022-07-01 19:48:08,904 - ERROR - cephci.test_upgrade:110 - string indices must be integers
Traceback (most recent call last):
  File "run.py", line 847, in run
    clients=clients,
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline/tests/upgrades/test_upgrade.py", line 229, in run
    config, version, is_repo_present, False
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline/tests/upgrades/test_upgrade.py", line 39, in get_ansible_conf
    release_info = get_release_repo(version)
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline/utility/utils.py", line 657, in get_release_repo
    repo_details = yaml.safe_load(data.text)[version]
TypeError: string indices must be integers

Error in file **test_upgrade.py** 
Logs for error - https://reportportal-rhcephqe.apps.ocp-c1.prod.psi.redhat.com/ui/#cephci/launches/5/4170/95749/95752/log?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.issueType%3Dti001%26launchesLimit%3D50%26isLatest%3Dfalse

**Comment by sunilangadi2** [comment]
In the release.yaml file 4.3 related info not exist Hence the script got failed,
Updated the http://magna002.ceph.redhat.com/cephci-jenkins/latest-rhceph-container-info/release.yaml as per 4.3 release RC changes also updated 5.0 and 5.1 latest RC info.

Test got passed
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-HN53NL/
