### ISSUE TITLE
Upgrade from RHCEPH-5.1 GA to same build is failing.

### ISSUE THREAD

**Issue by tintumathew10** [red-hat-storage/cephci#1626]
This issue is observed on 5.1 GA to 5.2 latest upgrade also.
BZ - https://bugzilla.redhat.com/show_bug.cgi?id=2104780.

2022-07-13 03:10:41,902 - ERROR - cephci.test_cephadm_upgrade:110 - Error 22 during cmd, timeout 600
2022-07-13 03:10:41,903 - ERROR - cephci.test_cephadm_upgrade:110 - cephadm -v shell -- ceph orch  --verbose upgrade start --image registry-proxy.engineering.redhat.com/rh-osbs/rhceph:ceph-5.1-rhel-8-containers-candidate-20720-20220624151827 Error:  --------------------------------------------------------------------------------
cephadm ['-v', 'shell', '--', 'ceph', 'orch', '--verbose', 'upgrade', 'start', '--image', 'registry-proxy.engineering.redhat.com/rh-osbs/rhceph:ceph-5.1-rhel-8-containers-candidate-20720-20220624151827']
/usr/bin/podman: 4.0.2

Error EINVAL: Upgrade to  (not registry-proxy.engineering.redhat.com/rh-osbs/rhceph:ceph-5.1-rhel-8-containers-candidate-20720-20220624151827) already in progress
 10.0.209.101
Traceback (most recent call last):
  File "/home/tmathew/ceph/cephci/tests/cephadm/test_cephadm_upgrade.py", line 68, in run
    orch.start_upgrade(config)
  File "/home/tmathew/ceph/cephci/ceph/ceph_admin/upgrade.py", line 56, in start_upgrade
    return self.shell(args=cmd)
  File "/home/tmathew/ceph/cephci/ceph/ceph_admin/shell.py", line 53, in shell
    long_running=long_running,
  File "/home/tmathew/ceph/cephci/ceph/ceph.py", line 2053, in exec_command
    return self.node.exec_command(cmd=cmd, **kw)
  File "/home/tmathew/ceph/cephci/ceph/ceph.py", line 1550, in exec_command
    f"{kw['cmd']} Error:  {str(stderr)} {str(self.ip_address)}"
ceph.ceph.CommandFailed: cephadm -v shell -- ceph orch  --verbose upgrade start --image registry-proxy.engineering.redhat.com/rh-osbs/rhceph:ceph-5.1-rhel-8-containers-candidate-20720-20220624151827 Error:  --------------------------------------------------------------------------------
cephadm ['-v', 'shell', '--', 'ceph', 'orch', '--verbose', 'upgrade', 'start', '--image', 'registry-proxy.engineering.redhat.com/rh-osbs/rhceph:ceph-5.1-rhel-8-containers-candidate-20720-20220624151827']
/usr/bin/podman: 4.0.2

cluster upgrade status

[ceph: root@ceph-tm1-51-upg-txdfra-node1-installer /]# ceph orch upgrade status
{
    "target_image": "",
    "in_progress": true,
    "services_complete": [],
    "progress": "",
    "message": "Error:  Warning, this RHCS release had multisite regressions. Please check the release notes"
}
[ceph: root@ceph-tm1-51-upg-txdfra-node1-installer /]# 

From cephci we need a workaround for continuing the upgrade.

Report portal link for failed issue.
https://reportportal-rhcephqe.apps.ocp-c1.prod.psi.redhat.com/ui/#cephci/launches/5/4262/99979

**Comment by tintumathew10** [comment]
closing this as we are not observing this issue now.
