### ISSUE TITLE
Rados suited failed to deploy cluster on 6.0 build

### ISSUE THREAD

**Issue by tintumathew10** [red-hat-storage/cephci#1680]
OSD deployment of ceph cluster on 6.0 downstream build is failing.

022-07-28 02:52:12,284 - ERROR - cephci.test_cephadm:110 - OSDs are not up and running in hosts
Traceback (most recent call last):
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline@2/tests/ceph_installer/test_cephadm.py", line 130, in run
    func(cfg)
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline@2/ceph/ceph_admin/osd.py", line 123, in apply
    raise OSDServiceFailure("OSDs are not up and running in hosts")
ceph.ceph_admin.osd.OSDServiceFailure: OSDs are not up and running in hosts
2022-07-28 02:52:12,285 - INFO - cephci.test_cephadm:110 - Running command cephadm -v shell -- ceph status on 10.245.5.12 timeout 600
2022-07-28 02:52:14,609 - INFO - cephci.test_cephadm:110 - Command completed successfully
2022-07-28 02:52:14,609 - DEBUG - cephci.test_cephadm:110 -   cluster:
    id:     b29c3160-0e1d-11ed-95a8-0219b01fc91e
    health: HEALTH_WARN
            Failed to apply 1 service(s): osd.all-available-devices
            OSD count 0 < osd_pool_default_size 3
 
  services:
    mon: 5 daemons, quorum ceph-ci-3bd66-zvndnd-node1-installer,ceph-ci-3bd66-zvndnd-node2,ceph-ci-3bd66-zvndnd-node6,ceph-ci-3bd66-zvndnd-node7,ceph-ci-3bd66-zvndnd-node11 (age 11m)
    mgr: ceph-ci-3bd66-zvndnd-node1-installer.yxkxzm(active, since 15m), standbys: ceph-ci-3bd66-zvndnd-node2.xrsyjg, ceph-ci-3bd66-zvndnd-node6.wxkwuc
    osd: 0 osds: 0 up, 0 in (since 7m)
 
  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     
 

2022-07-28 02:52:14,609 - INFO - cephci.test_cephadm:110 - STDOUT:
   cluster:
    id:     b29c3160-0e1d-11ed-95a8-0219b01fc91e
    health: HEALTH_WARN
            Failed to apply 1 service(s): osd.all-available-devices
            OSD count 0 < osd_pool_default_size 3
 
  services:
    mon: 5 daemons, quorum ceph-ci-3bd66-zvndnd-node1-installer,ceph-ci-3bd66-zvndnd-node2,ceph-ci-3bd66-zvndnd-node6,ceph-ci-3bd66-zvndnd-node7,ceph-ci-3bd66-zvndnd-node11 (age 11m)
    mgr: ceph-ci-3bd66-zvndnd-node1-installer.yxkxzm(active, since 15m), standbys: ceph-ci-3bd66-zvndnd-node2.xrsyjg, ceph-ci-3bd66-zvndnd-node6.wxkwuc
    osd: 0 osds: 0 up, 0 in (since 7m)
 
  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     

failed logs - https://reportportal-rhcephqe.apps.ocp-c1.prod.psi.redhat.com/ui/#cephci/launches/all/4419
Ceph Version: 17.2.2-1.el9cp

**Comment by tintumathew10** [comment]
BZ - https://bugzilla.redhat.com/show_bug.cgi?id=2114003

**Comment by tintumathew10** [comment]
This is a 6.0 BZ.
