### ISSUE TITLE
Timeout is happening in RADOS test cases

### ISSUE THREAD

**Issue by tintumathew10** [red-hat-storage/cephci#1726]
socket.timeout doesn't give an error message

The cluster did not reach active + Clean state

2022-08-13 14:51:26
 Execution failed at function <function wait_for_clean_pg_sets at 0x7f41b07ad1e0>
Traceback (most recent call last):
  File "run.py", line 850, in run
    clients=clients,
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline@4/tests/rados/test_osd_rebalance.py", line 94, in run
    method_should_succeed(wait_for_clean_pg_sets, rados_obj)
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline@4/utility/utils.py", line 1366, in method_should_succeed
    raise AssertionError(f"Execution failed at function {function}")
AssertionError: Execution failed at function <function wait_for_clean_pg_sets at 0x7f41b07ad1e0>

suite - [tier-3_rados_test-ecpool-osd-rebalance](https://reportportal-rhcephqe.apps.ocp-c1.prod.psi.redhat.com/ui/#cephci/launches/all/4664/111370)

**Comment by tintumathew10** [comment]
raised backlog for tracking this issue.
