### ISSUE TITLE
Snapshot reboot(tier-2_cephfs_test-snapshot-clone) failure

### ISSUE THREAD

**Issue by yogesh-mane** [red-hat-storage/cephci#1758]
**Describe the bug**
Script failure

**To Reproduce**
Run tier-2_cephfs_test-snapshot-clone suite 

**Expected behavior**
No errors

**Screenshots**
2022-08-20 16:32:27,574 - INFO - cephci.snapshot_clone.snapshot_reboot:110 - cd /mnt/cephfs_kernelje33dyjn75_2/;cp .snap/_snap_1_*/* . Error:  cp: cannot stat '.snap/_snap_1_*/*': No such file or directory
 10.245.7.192
2022-08-20 16:32:27,574 - INFO - cephci.snapshot_clone.snapshot_reboot:110 - Traceback (most recent call last):
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline@2/tests/cephfs/snapshot_clone/snapshot_reboot.py", line 111, in run
    sudo=True, cmd=f"cd {kernel_mounting_dir_2};cp .snap/_snap_1_*/* ."
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline@2/ceph/ceph.py", line 2051, in exec_command
    return self.node.exec_command(cmd=cmd, **kw)
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline@2/ceph/ceph.py", line 1548, in exec_command
    f"{kw['cmd']} Error:  {str(stderr)} {str(self.ip_address)}"
ceph.ceph.CommandFailed: cd /mnt/cephfs_kernelje33dyjn75_2/;cp .snap/_snap_1_*/* . Error:  cp: cannot stat '.snap/_snap_1_*/*': No such file or directory
 10.245.7.192

https://reportportal-rhcephqe.apps.ocp-c1.prod.psi.redhat.com/ui/#cephci/launches/all/4768/115089

**Comment by AmarnatReddy** [comment]
In Latest Builds we are not Observing this failure 
https://reportportal-rhcephqe.apps.ocp-c1.prod.psi.redhat.com/ui/#cephci/launches/all/5855/143269
