### ISSUE TITLE
RGW upgrade tier-1_rgw_upgrade_4x_to_6x_latest failed 

### ISSUE THREAD

**Issue by SrinivasaBharath** [red-hat-storage/cephci#1866]
**Describe the bug**
Script failed with the following  error-
2022-09-27 06:58:35,512 - ERROR - cephci.test_ansible:110 - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "run.py", line 850, in run
    clients=clients,
  File "/home/skanta/cephci_latest/cephci/tests/ceph_installer/test_ansible.py", line 127, in run
    exclude_ansible,
  File "/home/skanta/cephci_latest/cephci/ceph/ceph.py", line 814, in setup_packages
    node.setup_rhceph_cdn_repos(build, distro_ver)
  File "/home/skanta/cephci_latest/cephci/ceph/ceph.py", line 1818, in setup_rhceph_cdn_repos
    sudo=True, cmd="subscription-manager repos --enable={r}".format(r=repos[0])
TypeError: 'NoneType' object is not subscriptable

**To Reproduce**
Execute the following  CLI -
python3  run.py --osp-cred ~/osp-cred-ci-2.yaml --log-level debug  --rhbuild 6.0 --platform rhel-9 --global-conf conf/quincy/rgw/upgrades.yaml --inventory conf/inventory/rhel-9.0-server-x86_64.yaml  --suite suites/quincy/rgw/tier-1_rgw_upgrade_4x_to_6x_latest.yaml --skip-sos-report  --instances-name <instance_name>  --build latest  --store

Logs -   http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-OL01UV
--

**Comment by mkasturi18** [comment]
Closing this issue, as there is no support for n+2 upgrade. Also, the suite in question is removed from execution
