### ISSUE TITLE
Status failure is observed on IBM Pipeline

### ISSUE THREAD

**Issue by tintumathew10** [red-hat-storage/cephci#1937]
IBM pipeline fails with exception during cleanup.

https://159.23.92.24/job/rhceph-test-execution-pipeline/262/consoleFull

2022-11-04 00:31:44,174 - ERROR - cephci.utility.xunit:110 - Exception in parallel execution
Traceback (most recent call last):
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline@2/ceph/parallel.py", line 88, in __exit__
    for result in self:
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline@2/ceph/parallel.py", line 106, in __next__
    resurrect_traceback(result)
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline@2/ceph/parallel.py", line 35, in resurrect_traceback
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline@2/ceph/parallel.py", line 22, in capture_traceback
    return func(*args, **kwargs)
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline@2/compute/ibm_vpc.py", line 485, in delete
    self.remove_dns_records(zone_name)
  File "/data/jenkins/workspace/rhceph-test-execution-pipeline@2/compute/ibm_vpc.py", line 542, in remove_dns_records
    zones = self.dns_service.list_dnszones("a55534f5-678d-452d-8cc6-e780941d8e31")

**Comment by AmarnatReddy** [comment]
PR  https://github.com/red-hat-storage/cephci/pull/1977 
Address the isuue
