### ISSUE TITLE
Bug: cephci run is getting failed with --cloud_type baremetal where machine password is different than "passwd" 

### ISSUE THREAD

**Issue by udaysk23** [red-hat-storage/cephci#2159]
**Describe the bug**
cephci run is getting failed with --cloud_type baremetal where machine password is different than "passwd"  in yaml file

**To Reproduce**
Always

**Expected behavior**
Cephci should deploy baremetal cluster with any password since we are provding password in yaml file

**Environment**
NA

**Log snippet**
Since cephci is not generating any log link in this case, I am attaching log snippet below:

2023-02-03 09:31:52,209 (cephci.install_prereq) [DEBUG] - cephci.ceph.ceph.py:1257 - Retrying connection in 10 seconds
2023-02-03 09:32:02,223 (paramiko.transport) [INFO] - Connected (version 2.0, client OpenSSH_8.7)
2023-02-03 09:32:05,770 (paramiko.transport) [INFO] - Authentication (password) failed.
2023-02-03 09:32:05,772 (cephci.install_prereq) [WARNING] - cephci.ceph.ceph.py:1253 - Connection outage to 10.8.128.10: 
Authentication failed.
2023-02-03 09:32:05,774 (cephci.install_prereq) [DEBUG] - cephci.ceph.ceph.py:1257 - Retrying connection in 10 seconds
2023-02-03 09:32:15,788 (paramiko.transport) [INFO] - Connected (version 2.0, client OpenSSH_8.7)
2023-02-03 09:32:19,336 (paramiko.transport) [INFO] - Authentication (password) failed.
2023-02-03 09:32:19,338 (cephci.install_prereq) [WARNING] - cephci.ceph.ceph.py:1253 - Connection outage to 10.8.128.10: 
Authentication failed.
2023-02-03 09:32:19,340 (cephci.install_prereq) [DEBUG] - cephci.ceph.ceph.py:1257 - Retrying connection in 10 seconds
2023-02-03 09:32:29,353 (paramiko.transport) [INFO] - Connected (version 2.0, client OpenSSH_8.7)
2023-02-03 09:32:32,860 (paramiko.transport) [INFO] - Authentication (password) failed.
2023-02-03 09:32:32,862 (cephci.install_prereq) [WARNING] - cephci.ceph.ceph.py:1253 - Connection outage to 10.8.128.10: 
Authentication failed.
2023-02-03 09:32:32,864 (cephci.install_prereq) [DEBUG] - cephci.ceph.ceph.py:1257 - Retrying connection in 10 seconds
2023-02-03 09:32:42,878 (paramiko.transport) [INFO] - Connected (version 2.0, client OpenSSH_8.7)
2023-02-03 09:32:46,425 (paramiko.transport) [INFO] - Authentication (password) failed.
2023-02-03 09:32:46,427 (cephci.install_prereq) [WARNING] - cephci.ceph.ceph.py:1253 - Connection outage to 10.8.128.10: 
Authentication failed.
2023-02-03 09:32:46,429 (cephci.install_prereq) [DEBUG] - cephci.ceph.ceph.py:1257 - Retrying connection in 10 seconds
Traceback (most recent call last):
  File "run.py", line 1077, in <module>
    rc = run(args)
  File "run.py", line 892, in run
    collect_recipe(ceph_cluster_dict[cluster_name])
  File "run.py", line 1047, in collect_recipe
    sudo=True, cmd="podman --version | awk {'print $3'}", check_ec=False
  File "/home/ukurundw/bhima_deploy/cephci/ceph/ceph.py", line 2109, in exec_command
    return self.node.exec_command(cmd=cmd, **kw)
  File "/home/ukurundw/bhima_deploy/cephci/ceph/ceph.py", line 1538, in exec_command
    ssh = self.rssh() if kw.get("sudo") else self.ssh()
  File "/home/ukurundw/bhima_deploy/cephci/ceph/ceph.py", line 1233, in get_client
    self.__connect()
  File "/home/ukurundw/bhima_deploy/cephci/ceph/ceph.py", line 1260, in __connect
    raise AssertionError(f"Unable to establish connection with {self.ip_address}")
AssertionError: Unable to establish connection with 10.8.128.10

**Comment by vamahaja** [comment]
Fixed in PR https://github.com/red-hat-storage/cephci/pull/2170
