### ISSUE TITLE
Ceph test failures when RHEL compose changes

### ISSUE THREAD

**Issue by thom-at-redhat** [red-hat-storage/cephci#235]
As part of testing results in messages similar to:
"2020-10-09 02:06:18,677 - ceph.parallel - ERROR - Exception in parallel execution
Traceback (most recent call last):
File "/home/fedora/cephci/ceph/parallel.py", line 87, in _exit_
for result in self:
File "/home/fedora/cephci/ceph/parallel.py", line 105, in _next_
resurrect_traceback(result)
File "/home/fedora/cephci/ceph/parallel.py", line 34, in resurrect_traceback
raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
TypeError: _init_() missing 1 required positional argument: 'message'"

The first run of either RLP-ceph3.3-rhel7.9 or RLP-ceph4-rhel7.9 appear to run successfully. Subseqeunt runs fail with the above error 

https://github.com/red-hat-storage/cephci/blob/master/ceph/parallel.py
https://github.com/red-hat-storage/cephci/blob/master/ceph/ceph.py#L27

**Comment by thom-at-redhat** [comment]
As part of testing, results in messages similar to:
"2020-10-09 02:06:18,677 - ceph.parallel - ERROR - Exception in parallel execution
Traceback (most recent call last):
File "/home/fedora/cephci/ceph/parallel.py", line 87, in exit
for result in self:
File "/home/fedora/cephci/ceph/parallel.py", line 105, in next
resurrect_traceback(result)
File "/home/fedora/cephci/ceph/parallel.py", line 34, in resurrect_traceback
raise exc_info0.with_traceback(exc_info[2])
TypeError: init() missing 1 required positional argument: 'message'"

The first run of either RLP-ceph3.3-rhel7.9 or RLP-ceph4-rhel7.9 appear to run successfully. Subseqeunt runs fail with the above error 

https://github.com/red-hat-storage/cephci/blob/master/ceph/parallel.py
https://github.com/red-hat-storage/cephci/blob/master/ceph/ceph.py#L27

**Comment by thom-at-redhat** [comment]
Testing reveal FAIL occurs after using different compose

**Comment by thom-at-redhat** [comment]
"Traceback (most recent call last):",
    "  File \"run.py\", line 622, in <module>",
    "    rc = run(args)",
    "  File \"run.py\", line 415, in run",
    "    ceph_cluster_dict, clients = create_nodes(conf, inventory, osp_cred, run_id, service, instances_name)",
    "  File \"/home/fedora/cephci/utility/retry.py\", line 25, in f_retry",
    "    return f(*args, **kwargs)",
    "  File \"run.py\", line 137, in create_nodes",
    "    ceph_vmnodes = create_ceph_nodes(cluster, inventory, osp_cred, run_id, instances_name)",
    "  File \"/home/fedora/cephci/ceph/utils.py\", line 75, in create_ceph_nodes",
    "    p.spawn(setup_vm_node, node, ceph_nodes, **node_params)",
    "  File \"/home/fedora/cephci/ceph/parallel.py\", line 87, in __exit__",
    "    for result in self:",
    "  File \"/home/fedora/cephci/ceph/parallel.py\", line 105, in __next__",
    "    resurrect_traceback(result)",
    "  File \"/home/fedora/cephci/ceph/parallel.py\", line 34, in resurrect_traceback",
    "    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])",
    "TypeError: __init__() missing 1 required positional argument: 'message'"
