### ISSUE TITLE
Unclear how to resolve NodeErrorState

### ISSUE THREAD

**Issue by jennkimerson** [red-hat-storage/cephci#256]
There's no more information about this failure or how to fix it.

```
python run.py \
>   --rhbuild 4.2-rhel-7 \
>   --global-conf conf/nautilus/ansible/sanity-ceph-ansible-small.yaml \
>   --osp-cred osp/osp-cred-ci-2.yaml \
>   --inventory conf/inventory/rhel-7.8-server-x86_64.yaml \
>   --suite suites/nautilus/ansible/sanity_ceph_ansible_small.yaml \
>   --log-level info \
>   --ignore-latest-container

Note :
    1. Custom log directory will be disabled if '/ceph/cephci-jenkins' exists.
    2. If custom log directory not specified, then '/tmp' directory is considered .
    
Startup log location: /tmp/cephci-run-1604949358847/startup.log
2020-11-09 14:15:59,050 - __main__ - INFO - Compose id is: RHCEPH-4.2-RHEL-7-20201106.ci.0
2020-11-09 14:15:59,050 - __main__ - INFO - Testing Ceph Version: 14.2.11-73.el7cp
2020-11-09 14:15:59,050 - __main__ - INFO - Testing Ceph Ansible Version: 4.0.34.2-1.el7cp.noarch
2020-11-09 14:15:59,051 - __main__ - INFO - Destroying existing osp instances..
2020-11-09 14:16:12,561 - ceph.utils - INFO - Removing volume ceph-fedora-1604345088649-node4-osd2
2020-11-09 14:16:13,562 - ceph.utils - INFO - Removing volume ceph-fedora-1604345088649-node3-osd2
2020-11-09 14:16:14,563 - ceph.utils - INFO - Removing volume ceph-fedora-1604345088649-node2-osd2
2020-11-09 14:16:15,565 - ceph.utils - INFO - Removing volume ceph-fedora-1604345088649-node4-osd1
2020-11-09 14:16:16,566 - ceph.utils - INFO - Removing volume ceph-fedora-1604345088649-node3-osd1
2020-11-09 14:16:17,567 - ceph.utils - INFO - Removing volume ceph-fedora-1604345088649-node2-osd1
2020-11-09 14:16:18,568 - ceph.utils - INFO - Removing volume ceph-fedora-1604345088649-node4-osd0
2020-11-09 14:16:19,571 - ceph.utils - INFO - Removing volume ceph-fedora-1604345088649-node3-osd0
2020-11-09 14:16:20,572 - ceph.utils - INFO - Removing volume ceph-fedora-1604345088649-node2-osd0
2020-11-09 14:16:51,578 - ceph.utils - INFO - Done cleaning up volumes
2020-11-09 14:16:54,725 - ceph.utils - INFO - Destroying node ceph-fedora-1604345088649-node11-mgr with 0:05:00 timeout
2020-11-09 14:17:01,070 - ceph.utils - INFO - Destroying node ceph-fedora-1604345088649-node6-installer with 0:05:00 timeout
2020-11-09 14:17:07,226 - ceph.utils - INFO - Destroying node ceph-fedora-1604345088649-node3-osd with 0:05:00 timeout
2020-11-09 14:17:13,152 - ceph.utils - INFO - Destroying node ceph-fedora-1604345088649-node9-mon with 0:05:00 timeout
2020-11-09 14:17:18,753 - ceph.utils - INFO - Destroying node ceph-fedora-1604345088649-node8-rgw with 0:05:00 timeout
2020-11-09 14:17:24,714 - ceph.utils - INFO - Destroying node ceph-fedora-1604345088649-node2-osd with 0:05:00 timeout
2020-11-09 14:17:30,603 - ceph.utils - INFO - Destroying node ceph-fedora-1604345088649-node5-client with 0:05:00 timeout
2020-11-09 14:17:36,449 - ceph.utils - INFO - Destroying node ceph-fedora-1604345088649-node1-mon with 0:05:00 timeout
2020-11-09 14:17:41,767 - ceph.utils - INFO - Destroying node ceph-fedora-1604345088649-node10-mon with 0:05:00 timeout
2020-11-09 14:17:47,815 - ceph.utils - INFO - Destroying node ceph-fedora-1604345088649-node4-osd with 0:05:00 timeout
2020-11-09 14:17:53,233 - ceph.utils - INFO - Destroying node ceph-fedora-1604345088649-node7-mds with 0:05:00 timeout
2020-11-09 14:18:01,449 - ceph.utils - INFO - Done cleaning up nodes
2020-11-09 14:18:01,450 - __main__ - INFO - Creating osp instances
2020-11-09 14:18:18,725 - mita.openstack - INFO - created node: <Node: uuid=f3f4604366b57de18963b61d406fd5475d124362, name=ceph-fedora-1604949358847-node2-mon+client+osd, state=PENDING, public_ips=[], private_ips=[], provider=OpenStack ...>
2020-11-09 14:18:18,728 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node2-mon+client+osd to become available
2020-11-09 14:18:19,046 - mita.openstack - INFO - created node: <Node: uuid=70d56f4f862eba613093d4e0718c31936376c373, name=ceph-fedora-1604949358847-node3-mon+osd, state=PENDING, public_ips=[], private_ips=[], provider=OpenStack ...>
2020-11-09 14:18:19,047 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node3-mon+osd to become available
2020-11-09 14:18:19,235 - mita.openstack - INFO - created node: <Node: uuid=099b2e2824a76bc6fef482624c99c352a3e247dc, name=ceph-fedora-1604949358847-node1-mon+mgr+installer+osd, state=PENDING, public_ips=[], private_ips=[], provider=OpenStack ...>
2020-11-09 14:18:19,236 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node1-mon+mgr+installer+osd to become available
2020-11-09 14:18:36,549 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node2-mon+client+osd to become available
2020-11-09 14:18:38,929 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node3-mon+osd to become available
2020-11-09 14:18:39,208 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node1-mon+mgr+installer+osd to become available
2020-11-09 14:19:12,544 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node2-mon+client+osd to become available
2020-11-09 14:19:15,546 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node3-mon+osd to become available
2020-11-09 14:19:16,414 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node1-mon+mgr+installer+osd to become available
2020-11-09 14:19:45,211 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node2-mon+client+osd to become available
2020-11-09 14:19:48,638 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node3-mon+osd to become available
2020-11-09 14:19:54,120 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node1-mon+mgr+installer+osd to become available
2020-11-09 14:20:19,502 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node2-mon+client+osd to become available
2020-11-09 14:20:24,481 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node3-mon+osd to become available
2020-11-09 14:20:28,128 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node1-mon+mgr+installer+osd to become available
2020-11-09 14:20:54,083 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node2-mon+client+osd to become available
2020-11-09 14:20:57,799 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node3-mon+osd to become available
2020-11-09 14:21:01,689 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node1-mon+mgr+installer+osd to become available
2020-11-09 14:21:27,735 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node2-mon+client+osd to become available
2020-11-09 14:21:30,778 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node3-mon+osd to become available
2020-11-09 14:21:35,222 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node1-mon+mgr+installer+osd to become available
2020-11-09 14:22:00,109 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node2-mon+client+osd to become available
2020-11-09 14:22:03,708 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node3-mon+osd to become available
2020-11-09 14:22:09,588 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node1-mon+mgr+installer+osd to become available
2020-11-09 14:22:34,719 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node2-mon+client+osd to become available
2020-11-09 14:22:39,553 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node3-mon+osd to become available
2020-11-09 14:22:42,803 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node1-mon+mgr+installer+osd to become available
2020-11-09 14:23:08,252 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node2-mon+client+osd to become available
2020-11-09 14:23:12,045 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node3-mon+osd to become available
2020-11-09 14:23:18,700 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node1-mon+mgr+installer+osd to become available
2020-11-09 14:23:42,728 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node2-mon+client+osd to become available
2020-11-09 14:23:46,022 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node3-mon+osd to become available
2020-11-09 14:23:52,087 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node1-mon+mgr+installer+osd to become available
2020-11-09 14:24:16,080 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node2-mon+client+osd to become available
2020-11-09 14:24:20,504 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node3-mon+osd to become available
2020-11-09 14:24:25,520 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node1-mon+mgr+installer+osd to become available
2020-11-09 14:24:49,405 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node2-mon+client+osd to become available
2020-11-09 14:24:56,029 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node3-mon+osd to become available
2020-11-09 14:24:58,711 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node1-mon+mgr+installer+osd to become available
2020-11-09 14:25:22,026 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node2-mon+client+osd to become available
2020-11-09 14:25:29,302 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node3-mon+osd to become available
2020-11-09 14:25:34,819 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node1-mon+mgr+installer+osd to become available
2020-11-09 14:25:57,606 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node2-mon+client+osd to become available
2020-11-09 14:26:02,554 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node3-mon+osd to become available
2020-11-09 14:26:13,418 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node1-mon+mgr+installer+osd to become available
2020-11-09 14:26:30,283 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node2-mon+client+osd to become available
2020-11-09 14:26:40,147 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node3-mon+osd to become available
2020-11-09 14:26:46,355 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node1-mon+mgr+installer+osd to become available
2020-11-09 14:27:04,295 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node2-mon+client+osd to become available
2020-11-09 14:27:19,108 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node3-mon+osd to become available
2020-11-09 14:27:25,009 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node1-mon+mgr+installer+osd to become available
2020-11-09 14:27:37,338 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node2-mon+client+osd to become available
2020-11-09 14:27:52,909 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node3-mon+osd to become available
2020-11-09 14:27:57,721 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node1-mon+mgr+installer+osd to become available
2020-11-09 14:28:12,121 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node2-mon+client+osd to become available
2020-11-09 14:28:29,000 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node3-mon+osd to become available
2020-11-09 14:28:33,494 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node1-mon+mgr+installer+osd to become available
2020-11-09 14:28:39,969 - mita.openstack - INFO - Failed to bring the node in running state in 0:10:00s
2020-11-09 14:28:51,523 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node2-mon+client+osd to become available
2020-11-09 14:28:54,415 - mita.openstack - INFO - Failed to bring the node in running state in 0:10:00s
2020-11-09 14:29:04,999 - mita.openstack - INFO - Waiting for node ceph-fedora-1604949358847-node3-mon+osd to become available
2020-11-09 14:29:17,154 - mita.openstack - INFO - Failed to bring the node in running state in 0:10:00s
2020-11-09 14:29:17,154 - ceph.parallel - ERROR - Exception in parallel execution
Traceback (most recent call last):
  File "/home/fedora/cephci/ceph/parallel.py", line 87, in __exit__
    for result in self:
  File "/home/fedora/cephci/ceph/parallel.py", line 105, in __next__
    resurrect_traceback(result)
  File "/home/fedora/cephci/ceph/parallel.py", line 34, in resurrect_traceback
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "/home/fedora/cephci/ceph/parallel.py", line 21, in capture_traceback
    return func(*args, **kwargs)
  File "/home/fedora/cephci/ceph/utils.py", line 81, in setup_vm_node
    ceph_nodes[node] = CephVMNode(**params)
  File "/home/fedora/cephci/mita/openstack.py", line 70, in __init__
    self.create_node()
  File "/home/fedora/cephci/mita/openstack.py", line 179, in create_node
    raise NodeErrorState("Failed to bring up the node in Running state " + name)
mita.openstack.NodeErrorState: Failed to bring up the node in Running state ceph-fedora-1604949358847-node1-mon+mgr+installer+osd
Traceback (most recent call last):
  File "run.py", line 622, in <module>
    rc = run(args)
  File "run.py", line 415, in run
    ceph_cluster_dict, clients = create_nodes(conf, inventory, osp_cred, run_id, service, instances_name)
  File "/home/fedora/cephci/utility/retry.py", line 25, in f_retry
    return f(*args, **kwargs)
  File "run.py", line 137, in create_nodes
    ceph_vmnodes = create_ceph_nodes(cluster, inventory, osp_cred, run_id, instances_name)
  File "/home/fedora/cephci/ceph/utils.py", line 75, in create_ceph_nodes
    p.spawn(setup_vm_node, node, ceph_nodes, **node_params)
  File "/home/fedora/cephci/ceph/parallel.py", line 87, in __exit__
    for result in self:
  File "/home/fedora/cephci/ceph/parallel.py", line 105, in __next__
    resurrect_traceback(result)
  File "/home/fedora/cephci/ceph/parallel.py", line 34, in resurrect_traceback
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "/home/fedora/cephci/ceph/parallel.py", line 21, in capture_traceback
    return func(*args, **kwargs)
  File "/home/fedora/cephci/ceph/utils.py", line 81, in setup_vm_node
    ceph_nodes[node] = CephVMNode(**params)
  File "/home/fedora/cephci/mita/openstack.py", line 70, in __init__
    self.create_node()
  File "/home/fedora/cephci/mita/openstack.py", line 179, in create_node
    raise NodeErrorState("Failed to bring up the node in Running state " + name)
mita.openstack.NodeErrorState: Failed to bring up the node in Running state ceph-fedora-1604949358847-node1-mon+mgr+installer+osd
```

**Comment by ktdreyer** [comment]
We need more information beyond a general "`Failed to bring up the node`" message.

Does libcloud give us an error message from OpenStack about why this node failed to come up?

**Comment by jennkimerson** [comment]
https://github.com/red-hat-storage/cephci/pull/257

**Comment by ktdreyer** [comment]
Jennifer, since merging #257, have you seen this error any more?
