### ISSUE TITLE
"Image rhel-7.8-server-x86_64-released not found"

### ISSUE THREAD

**Issue by ktdreyer** [red-hat-storage/cephci#288]
I'm seeing the following crash:

```
2021-01-07 13:28:12,720 - __main__ - INFO - Creating osp instances
2021-01-07 13:28:12,721 - mita.openstack - INFO - Instantiating VM with name ceph-kdreyer-1610044052623-node1-mon+mgr+installer+osd
2021-01-07 13:28:12,723 - mita.openstack - INFO - Instantiating VM with name ceph-kdreyer-1610044052623-node2-mon+client+osd
2021-01-07 13:28:12,725 - mita.openstack - INFO - Instantiating VM with name ceph-kdreyer-1610044052623-node3-mon+osd
2021-01-07 13:28:14,246 - mita.openstack - ERROR - Image rhel-7.8-server-x86_64-released not found
2021-01-07 13:28:14,674 - mita.openstack - ERROR - Image rhel-7.8-server-x86_64-released not found
2021-01-07 13:28:14,697 - mita.openstack - ERROR - Image rhel-7.8-server-x86_64-released not found
2021-01-07 13:28:14,698 - ceph.parallel - ERROR - Exception in parallel execution
Traceback (most recent call last):
  File "/home/kdreyer/cephci/ceph/parallel.py", line 87, in __exit__
    for result in self:
  File "/home/kdreyer/cephci/ceph/parallel.py", line 105, in __next__
    resurrect_traceback(result)
  File "/home/kdreyer/cephci/ceph/parallel.py", line 34, in resurrect_traceback
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "/home/kdreyer/cephci/ceph/parallel.py", line 21, in capture_traceback
    return func(*args, **kwargs)
  File "/home/kdreyer/cephci/ceph/utils.py", line 81, in setup_vm_node
    ceph_nodes[node] = CephVMNode(**params)
  File "/home/kdreyer/cephci/mita/openstack.py", line 99, in __init__
    self.create_node()
  File "/home/kdreyer/cephci/mita/openstack.py", line 390, in create_node
    self._create_vm_node()
  File "/home/kdreyer/cephci/mita/openstack.py", line 263, in _create_vm_node
    raise NodeErrorState("Failed to create the instance {}".format(self.node_name))
mita.openstack.NodeErrorState: Failed to create the instance ceph-kdreyer-1610044052623-node3-mon+osd
```

The image does exist though, and I can view it with the OpenStack CLI with `openstack image show rhel-7.8-server-x86_64-released`. It says `updated_at 2020-12-06T12:34:03Z`

**Comment by ktdreyer** [comment]
After I deleted my virtualenv and re-initialized it, I cannot reproduce this error any more.
