### ISSUE TITLE
RBD_Mirror tests are failing for RHCS 4.2

### ISSUE THREAD

**Issue by veera-raghava-reddy** [red-hat-storage/cephci#300]
RBD_Mirror tests are failing for RHCS 4.2

http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1610512920091/result.html

2021-01-13 00:23:26,425 - utility.utils - INFO - Completed log configuration
2021-01-13 00:23:26,427 - __main__ - INFO - Running test test_9470.py
2021-01-13 00:23:26,427 - test_9470 - INFO - Starting CEPH-9470
2021-01-13 00:23:26,427 - ceph.ceph - INFO - Running command ceph osd pool create SaXPSdEDUU9470pool 64 64 --cluster master on 10.0.101.45
2021-01-13 00:23:27,783 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:23:27,783 - ceph.ceph - INFO - Running command rbd pool init SaXPSdEDUU9470pool --cluster master on 10.0.101.45
2021-01-13 00:23:30,841 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:23:30,842 - ceph.ceph - INFO - Running command ceph osd pool create SaXPSdEDUU9470pool 64 64 --cluster slave on 10.0.102.79
2021-01-13 00:23:32,429 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:23:32,430 - ceph.ceph - INFO - Running command rbd pool init SaXPSdEDUU9470pool --cluster slave on 10.0.102.79
2021-01-13 00:23:35,503 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:23:35,503 - ceph.ceph - INFO - Running command rbd create -s 2G SaXPSdEDUU9470pool/EePmRrkKRv9470image --image-feature exclusive-lock,journaling --cluster master on 10.0.101.45
2021-01-13 00:23:35,674 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:23:35,675 - ceph.ceph - INFO - Running command rbd mirror pool enable SaXPSdEDUU9470pool pool --cluster master on 10.0.101.45
2021-01-13 00:23:35,884 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:23:35,884 - ceph.ceph - INFO - Running command rbd mirror pool enable SaXPSdEDUU9470pool pool --cluster slave on 10.0.102.79
2021-01-13 00:23:36,018 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:23:36,018 - ceph.ceph - INFO - Running command rbd mirror pool peer add SaXPSdEDUU9470pool client.admin@slave --cluster master on 10.0.101.45
2021-01-13 00:23:36,171 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:23:36,172 - ceph.ceph - INFO - Running command rbd mirror pool peer add SaXPSdEDUU9470pool client.admin@master --cluster slave on 10.0.102.79
2021-01-13 00:23:36,301 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:23:36,301 - ceph.ceph - INFO - Running command rbd mirror pool info SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:23:36,402 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:23:36,403 - ceph.ceph - INFO - Running command rbd mirror pool info SaXPSdEDUU9470pool --format=json --cluster slave on 10.0.102.79
2021-01-13 00:23:36,508 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:23:36,509 - tests.rbd_mirror.rbd_mirror_utils - INFO - Peers were successfully added
2021-01-13 00:23:36,509 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:23:36,610 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:23:36,610 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: ERROR
2021-01-13 00:23:56,610 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:23:56,707 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:23:56,707 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:24:16,708 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:24:16,813 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:24:16,813 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:24:36,815 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:24:36,917 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:24:36,918 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:24:56,919 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:24:57,027 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:24:57,028 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:25:17,029 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:25:17,135 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:25:17,136 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:25:37,137 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:25:37,242 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:25:37,242 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:25:57,243 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:25:57,342 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:25:57,342 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:26:17,343 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:26:17,454 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:26:17,454 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:26:37,455 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:26:37,573 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:26:37,573 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:26:57,574 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:26:57,677 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:26:57,678 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:27:17,679 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:27:17,779 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:27:17,779 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:27:37,780 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:27:37,883 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:27:37,883 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:27:57,884 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:27:57,986 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:27:57,986 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:28:17,987 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:28:18,085 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:28:18,086 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:28:38,086 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:28:38,191 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:28:38,191 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:28:58,191 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:28:58,295 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:28:58,296 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:29:18,296 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:29:18,402 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:29:18,402 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:29:38,403 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:29:38,502 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:29:38,502 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:29:58,503 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:29:58,631 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:29:58,631 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:30:18,632 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:30:18,735 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:30:18,735 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:30:38,736 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:30:38,844 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:30:38,844 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:30:58,845 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:30:58,948 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:30:58,949 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:31:18,949 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:31:19,051 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:31:19,051 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:31:39,051 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:31:39,150 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:31:39,150 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:31:59,151 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:31:59,248 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:31:59,248 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:32:19,249 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:32:19,353 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:32:19,353 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:32:39,354 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:32:39,454 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:32:39,454 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:32:59,455 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:32:59,556 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:32:59,557 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:33:19,558 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:33:19,661 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:33:19,661 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:33:39,662 - ceph.ceph - INFO - Running command rbd mirror pool status SaXPSdEDUU9470pool --format=json --cluster master on 10.0.101.45
2021-01-13 00:33:39,771 - ceph.ceph - INFO - Command completed successfully
2021-01-13 00:33:39,771 - tests.rbd_mirror.rbd_mirror_utils - INFO - Health of SaXPSdEDUU9470pool pool in master cluster: WARNING
2021-01-13 00:33:39,772 - test_9470 - ERROR - Required status can not be attained
Traceback (most recent call last):
  File "/home/rhcs-jslave1/workspace/CEPH-RBD@2/c8e26a7a-85f7-40ab-8281-9836e6bc936e/tests/rbd_mirror/test_9470.py", line 24, in run
    mirror1.config_mirror(mirror2, poolname=poolname, mode='pool')
  File "/home/rhcs-jslave1/workspace/CEPH-RBD@2/c8e26a7a-85f7-40ab-8281-9836e6bc936e/tests/rbd_mirror/rbd_mirror_utils.py", line 162, in config_mirror
    self.wait_for_status(poolname=poolname, health_pattern='OK')
  File "/home/rhcs-jslave1/workspace/CEPH-RBD@2/c8e26a7a-85f7-40ab-8281-9836e6bc936e/tests/rbd_mirror/rbd_mirror_utils.py", line 216, in wait_for_status
    raise Exception("Required status can not be attained")
Exception: Required status can not be attained
2021-01-13 00:33:39,772 - __main__ - INFO - Test <module 'test_9470' from '/home/rhcs-jslave1/workspace/CEPH-RBD@2/c8e26a7a-85f7-40ab-8281-9836e6bc936e/tests/rbd_mirror/test_9470.py'> failed
2021-01-13 00:33:39,774 - utility.utils - INFO - Test logfile: /ceph/cephci-jenkins/cephci-run-1610512920091/test_9471_0.log

**Comment by veera-raghava-reddy** [comment]
Working in latest runs
