### ISSUE TITLE
cephci execution fails occasionally while creating nodes

### ISSUE THREAD

**Issue by manasagowri** [red-hat-storage/cephci#309]
cephci execution fails occasionally while creating nodes. A rerun sometimes results in a success. 
PFB the error message for one such failures.

2021-01-18 00:40:51,710 - ceph.parallel - ERROR - Exception in parallel execution
Traceback (most recent call last):
  File "/home/rhcs-jslave1/workspace/CEPH-RGW@2/368b99b8-7c11-4ccf-8776-3a3cae1cfd68/ceph/parallel.py", line 87, in __exit__
    for result in self:
  File "/home/rhcs-jslave1/workspace/CEPH-RGW@2/368b99b8-7c11-4ccf-8776-3a3cae1cfd68/ceph/parallel.py", line 105, in __next__
    resurrect_traceback(result)
  File "/home/rhcs-jslave1/workspace/CEPH-RGW@2/368b99b8-7c11-4ccf-8776-3a3cae1cfd68/ceph/parallel.py", line 34, in resurrect_traceback
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
TypeError: __init__() missing 1 required positional argument: 'message'
2021-01-18 00:40:51,711 - __main__ - ERROR - __init__() missing 1 required positional argument: 'message'
2021-01-18 00:40:51,801 - utility.utils - INFO - Results have been emailed to ['cephci@redhat.com']
Traceback (most recent call last):
  File "run.py", line 660, in <module>
    log.info("final rc of test run %d" % rc)
TypeError: %d format: a number is required, not NoneType

**Comment by psathyan** [comment]
I observe multiple problems here

- `TypeError` exception due to missing `message`
- `TypeError` exception due to `NoneType`
- Soft errors, we could attempt to retry

**Comment by psathyan** [comment]
#320 addresses point 1.
