### ISSUE TITLE
crash warning upon daemon crash failed

### ISSUE THREAD

**Issue by krishnaramaswamy** [red-hat-storage/cephci#3118]
crash warning upon daemon crash failed
polarian: https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83573855

Here is the log:
2023-11-08 20:29:48,560 (cephci.test_crash_daemon) [ERROR] - cephci.Sanity.138.cephci.tests.rados.monitor_configurations.py:326 - The Config: mgr/crash/retain_interval not listed under in the dump
2023-11-08 20:29:48,561 (cephci.test_crash_daemon) [INFO] - cephci.Sanity.138.cephci.tests.rados.monitor_configurations.py:261 - Value for config: mgr/crash/retain_interval was removed
2023-11-08 20:29:48,561 (cephci.test_crash_daemon) [ERROR] - cephci.Sanity.138.cephci.run.py:800 - 'RadosOrchestrator' object has no attribute 'configure_host_as_client'
Traceback (most recent call last):
  File "/home/jenkins/ceph-builds/18.2.0-119/Sanity/138/cephci/run.py", line 784, in run
    rc = test_mod.run(
  File "/home/jenkins/ceph-builds/18.2.0-119/Sanity/138/cephci/tests/rados/test_crash_daemon.py", line 42, in run
    assert rados_obj.crash_ceph_daemon(daemon="osd", id=osd_id, manual_inject=True)
  File "/home/jenkins/ceph-builds/18.2.0-119/Sanity/138/cephci/ceph/rados/core_workflows.py", line 2286, in crash_ceph_daemon
    self.configure_host_as_client(daemon_host)
AttributeError: 'RadosOrchestrator' object has no attribute 'configure_host_as_client'
2023-11-08 20:29:48,562 (cephci.test_crash_daemon) [INFO] - cephci.Sanity.138.cephci.ceph.ceph.py:1557 - Running command podman --version | awk {'print $3'} on 10.0.195.161 timeout 600
2023-11-08 20:29:49,246 (cephci.test_crash_daemon) [INFO] - cephci.Sanity.138.cephci.run.py:996 - Podman Version 4.4.1
2023-11-08 20:29:49,247 (cephci.test_crash_daemon) [INFO] - cephci.Sanity.138.cephci.ceph.ceph.py:1557 - Running command docker --version | awk {'print $3'} on 10.0.195.161 timeout 600
2023-11-08 20:29:49,916 (cephci.test_crash_daemon) [INFO] - cephci.Sanity.138.cephci.ceph.ceph.py:1557 - Running command ceph --version | awk '{print $3}' on 10.0.195.89 timeout 600
2023-11-08 20:29:50,410 (cephci.test_crash_daemon) [INFO] - cephci.Sanity.138.cephci.run.py:1012 - ceph Version 18.2.0-119.el9cp
2023-11-08 20:29:50,411 (cephci.test_crash_daemon) [INFO] - cephci.Sanity.138.cephci.run.py:971 - ceph_clusters_file rerun/sanity-sqlMB5-V156TP
2023-11-08 20:29:50,411 (cephci.test_crash_daemon) [INFO] - cephci.Sanity.138.cephci.run.py:865 - Test <module 'test_crash_daemon' from '/home/jenkins/ceph-builds/18.2.0-119/Sanity/138/cephci/tests/rados/test_crash_daemon.py'> failed

**Comment by neha-gangadhar** [comment]
hi @krishnaramaswamy The test initially failed for automation issue which when fixed turned out to be a product issue later. We are tracking the test and failures in CI in JIRA. 
BZ for ref: https://bugzilla.redhat.com/show_bug.cgi?id=2253394 
Closing the issue as no cephci enhancement is needed.
