### ISSUE TITLE
Cephfs test cases are failing with script issues

### ISSUE THREAD

**Issue by AmarnatReddy** [red-hat-storage/cephci#461]
Two Test cases are failing.

Failure Logs : 
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1618906354977/result.html

1. cephfs-stressIO
     Test case is failing with script Error
2021-04-20 04:16:21,827 - CEPH-11222_11223 - INFO - Traceback (most recent call last):
  File "/home/amk/PR_462/cephci_1/tests/cephfs/CEPH-11222_11223.py", line 217, in run
    for op in p:
  File "/home/amk/PR_462/cephci_1/ceph/parallel.py", line 105, in __next__
    resurrect_traceback(result)
  File "/home/amk/PR_462/cephci_1/ceph/parallel.py", line 34, in resurrect_traceback
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "/home/amk/PR_462/cephci_1/ceph/parallel.py", line 21, in capture_traceback
    return func(*args, **kwargs)
  File "/home/amk/PR_462/cephci_1/tests/cephfs/cephfs_utils.py", line 1126, in stress_io
    % (mounting_dir, dir_name, range1, range2),
  File "/home/amk/PR_462/cephci_1/ceph/ceph.py", line 1872, in exec_command
    return self.node.exec_command(cmd=cmd, **kw)
  File "/home/amk/PR_462/cephci_1/ceph/ceph.py", line 1389, in exec_command
    + str(self.ip_address)
ceph.ceph.CommandFailed: sh -c 'cd /mnt/cephfs_4711bd90dl/olqzp5ggnn && sudo touch {0..100}.txt' Error:  sh: line 0: cd: /mnt/cephfs_4711bd90dl/olqzp5ggnn: No such file or directory
 10.0.208.116
2. OSD-failure 
 ceph cluster health status is not becoming normal after the test case

**Comment by rakeshgm** [comment]
issue fixed. PR is linked above.
