### ISSUE TITLE
cephadm is intervening in 4.x scripts.

### ISSUE THREAD

**Issue by manasagowri** [red-hat-storage/cephci#469]
While executing upgrade_containerized suite for 4.x, cephadm gave an error.

http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1619152243856/rgw_sanity_tests_0.log

2021-04-23 01:52:36,764 - ceph.ceph - INFO - Running command cephadm shell -- ceph auth get client.admin on 10.0.210.232
2021-04-23 01:52:36,785 - ceph.ceph - ERROR - Error 127 during cmd, timeout 120
2021-04-23 01:52:36,786 - __main__ - ERROR - Traceback (most recent call last):
  File "run.py", line 817, in run
    clients=clients,
  File "/home/rhcs-jslave1/workspace/CEPH-Deployment@3/bfee6d64-63d4-4529-83e0-71b25a356296/tests/rgw/sanity_rgw.py", line 66, in run
    setup_cluster_access(ceph_cluster, rgw_node)
  File "/home/rhcs-jslave1/workspace/CEPH-Deployment@3/bfee6d64-63d4-4529-83e0-71b25a356296/utility/utils.py", line 836, in setup_cluster_access
    out, err = installer_node.exec_command(sudo=True, cmd=command)
  File "/home/rhcs-jslave1/workspace/CEPH-Deployment@3/bfee6d64-63d4-4529-83e0-71b25a356296/ceph/ceph.py", line 1389, in exec_command
    + str(self.ip_address)
ceph.ceph.CommandFailed: cephadm shell -- ceph auth get client.admin Error:  bash: cephadm: command not found
 10.0.210.232

**Comment by rakeshgm** [comment]
Ah, I see the issue, the above run is a container test. this [line](https://github.com/red-hat-storage/cephci/blob/master/tests/rgw/sanity_rgw.py#L65) is returning `True` because it is containerised. 
This [funtion](https://github.com/red-hat-storage/cephci/blob/master/utility/utils.py#L804) has cephadm shell commands
