### ISSUE TITLE
sanity_ceph_ansible suite execution failed with UnicodeDecodeError

### ISSUE THREAD

**Issue by manasagowri** [red-hat-storage/cephci#479]
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1619584373779/ceph_ansible_0.log

2021-04-28 01:25:31,010 - __main__ - ERROR - Traceback (most recent call last):
  File "run.py", line 814, in run
    clients=clients,
  File "/home/rhcs-jslave1/workspace/CEPH-Deployment@2/c950087c-87cc-4904-ad86-7b91feec9a1c/tests/ceph_installer/test_ansible.py", line 96, in run
    long_running=True,
  File "/home/rhcs-jslave1/workspace/CEPH-Deployment@2/c950087c-87cc-4904-ad86-7b91feec9a1c/ceph/ceph.py", line 1872, in exec_command
    return self.node.exec_command(cmd=cmd, **kw)
  File "/home/rhcs-jslave1/workspace/CEPH-Deployment@2/c950087c-87cc-4904-ad86-7b91feec9a1c/ceph/ceph.py", line 1364, in exec_command
    read += data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 1022-1023: unexpected end of data

**Comment by ckulal** [comment]
Seen same issue.
find the log:
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-Q5VZEV/
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-I80KC5/

**Comment by rakeshgm** [comment]
@manasagowri @ckulal any update on this. are you still seeing this issue now.

**Comment by ckulal** [comment]
Hi @rakeshgm ,
Currently I am not seeing this issue.

**Comment by rakeshgm** [comment]
Can you close the issue then.

**Comment by ckulal** [comment]
Will be closing this issue as we are not observing failures in recent runs.Will create an issue if failure observed in future.
