### ISSUE TITLE
Interop test run fails with no suitable interface is found

### ISSUE THREAD

**Issue by pdhiran** [red-hat-storage/cephci#884]
https://main-jenkins-csb-interopqe.apps.ocp4.prod.psi.redhat.com/job/ceph-4-rhel-8/17/artifact/.results/artifacts/ceph-driver-zbybm/cephci-run.log/*view*/

error snippet
``` 2021-10-21 13:59:16,488 - ceph.ceph - ERROR - Error 1 during cmd, timeout 120
2021-10-21 13:59:16,488 - ceph.ceph - INFO - No suitable ethernet interface found on 10.0.211.112
2021-10-21 13:59:16,488 - ceph.ceph - ERROR - Network test failed: No suitable interface is found on 10.0.208.120.
2021-10-21 13:59:16,489 - __main__ - ERROR - Traceback (most recent call last):
  File "run.py", line 902, in run
    clients=clients,
  File "/home/fedora/cephci/tests/ceph_installer/test_ansible.py", line 69, in run
    device_to_add, mixed_lvm_configs, filestore
  File "/home/fedora/cephci/ceph/ceph.py", line 239, in generate_ansible_inventory
    raise RuntimeError(err)
RuntimeError: Network test failed: No suitable interface is found on 10.0.208.120. ```

**Comment by veera-raghava-reddy** [comment]
@psathyan Can this issue be closed, or should we check with Inter-op to rerun and confirm if the test run completes without issues?

**Comment by psathyan** [comment]
Closing this issue as it is outside our scope
